// Die größten gesetzlichen Krankenkassen (GKV) in Deutschland - deckt die
// überwiegende Mehrheit der gesetzlich Versicherten ab. Keine erschöpfende
// Liste aller ~95 Kassen (u.a. viele kleine firmeneigene Betriebskrankenkassen
// fehlen), deshalb immer mit "Andere gesetzliche Krankenkasse" abschließen,
// die im Formular ein Freitextfeld öffnet statt jemanden zu blockieren.
export const GESETZLICHE_KRANKENKASSEN = [
  "AOK Baden-Württemberg",
  "AOK Bayern",
  "AOK Bremen/Bremerhaven",
  "AOK Hessen",
  "AOK Niedersachsen",
  "AOK Nordost",
  "AOK NordWest",
  "AOK PLUS",
  "AOK Rheinland/Hamburg",
  "AOK Rheinland-Pfalz/Saarland",
  "AOK Sachsen-Anhalt",
  "Techniker Krankenkasse (TK)",
  "Barmer",
  "DAK-Gesundheit",
  "IKK classic",
  "IKK Brandenburg und Berlin",
  "IKK gesund plus",
  "IKK Südwest",
  "KKH Kaufmännische Krankenkasse",
  "Knappschaft",
  "hkk (Handelskrankenkasse)",
  "HEK - Hanseatische Krankenkasse",
  "SBK (Siemens-Betriebskrankenkasse)",
  "BIG direkt gesund",
  "BKK Mobil Oil",
  "BKK VBU",
  "BKK firmus",
  "Bosch BKK",
  "Audi BKK",
  "Mercedes-Benz BKK",
  "Novitas BKK",
  "Pronova BKK",
  "Viactiv Krankenkasse",
  "Andere gesetzliche Krankenkasse",
] as const;
