// Kept in sync with apps/web/lib/krankenkassen.ts - not shared via a
// package since it's presentation-layer copy, not a validated shape.
export const GESETZLICHE_KRANKENKASSEN = [
  "AOK Baden-Württemberg",
  "AOK Bayern",
  "AOK Bremen/Bremerhaven",
  "AOK Hessen",
  "AOK Niedersachsen",
  "AOK Nordost",
  "AOK NordWest",
  "AOK PLUS",
  "AOK Rheinland/Hamburg",
  "AOK Rheinland-Pfalz/Saarland",
  "AOK Sachsen-Anhalt",
  "Techniker Krankenkasse (TK)",
  "Barmer",
  "DAK-Gesundheit",
  "IKK classic",
  "IKK Brandenburg und Berlin",
  "IKK gesund plus",
  "IKK Südwest",
  "KKH Kaufmännische Krankenkasse",
  "Knappschaft",
  "hkk (Handelskrankenkasse)",
  "HEK - Hanseatische Krankenkasse",
  "SBK (Siemens-Betriebskrankenkasse)",
  "BIG direkt gesund",
  "BKK Mobil Oil",
  "BKK VBU",
  "BKK firmus",
  "Bosch BKK",
  "Audi BKK",
  "Mercedes-Benz BKK",
  "Novitas BKK",
  "Pronova BKK",
  "Viactiv Krankenkasse",
  "Andere gesetzliche Krankenkasse",
] as const;
